### ISSUE TITLE
Add a section to the readme about how you compare to hashids

### ISSUE THREAD

**Issue by trashhalo** [sqids/sqids-elixir#10]
It would be helpful to users who are familiar with the existing elixir hashid lib https://github.com/alco/hashids-elixir to know how you compare.

**Comment by 4kimov** [comment]
Does this help? https://github.com/hashids/#what-is-changing

**Comment by 4kimov** [comment]
No, it's not linked in the READMEs of individual implementations, but it is linked generally on the Hashids side.

Discussion here: https://github.com/orgs/hashids/discussions/92
Main notice here: https://github.com/hashids
Bar at the top of the site, example: https://hashids.org/javascript
