### ISSUE TITLE
Assertion raises because ExUnit is missing

### ISSUE THREAD

**Issue by tshakah** [sqids/sqids-elixir#19]
I've just tried integrating this into an app as I like the ID format, but it crashes in production due to the `assert` you are using from ExUnit. It would be great to have something in the docs about this, although I'd argue you shouldn't be using it in non-test code

This was the error:
```
    ** (UndefinedFunctionError) function ExUnit.Assertions.__equal__?/2 is undefined (module ExUnit.Assertions is not available)
        ExUnit.Assertions.__equal__?(22, nil)
        (sqids 0.1.2) lib/sqids/alphabet.ex:113: Sqids.Alphabet.index_of!/2
        (sqids 0.1.2) lib/sqids.ex:426: Sqids.decode_valid_id/2
        (sqids 0.1.2) lib/sqids.ex:165: Sqids.decode!/2
```

I'm using the [compile time config](https://hexdocs.pm/sqids/readme.html#convenience-create-context-at-compile-time)

**Comment by g-andrade** [comment]
Hi,

The assertion is there as a sanity check - it's like a guard, only one that's more informative (it makes sure that the `known_symbol?` function was invoked before getting that far in decoding).

In any case: the error message suggests ExUnit is missing, not that the assertion is failing. Maybe I forgot to include it in `mix.exs`... thanks for raising the issue, I'll look into it soon!

**Comment by g-andrade** [comment]
I think my theory is right, `ex_unit` is missing from Sqids's `extra_applications` in `mix.exs` (there's no `extra_applications` at all, in fact). I forgot that it's a separate application... maybe I will indeed just switch it to an if+raise.

In the mean time, if you add/merge `extra_applications: [:ex_unit]` to your own `mix.exs`, this should work around the issue.

**Comment by tshakah** [comment]
Thanks, in the mean time I actually forked and updated to do something like the former: https://github.com/sqids/sqids-elixir/compare/main...tshakah:sqids-elixir:main. I can create a PR if you want

**Comment by g-andrade** [comment]
Yup that works, thanks!

**Comment by tshakah** [comment]
No worries :) https://github.com/sqids/sqids-elixir/pull/20
