### ISSUE TITLE
Enable automatic updates to default blocklist

### ISSUE THREAD

**Issue by g-andrade** [sqids/sqids-elixir#3]
This is setup as [a GHA workflow](https://github.com/sqids/sqids-elixir/blob/f0b7a73/.github/workflows/default-blocklist-updater.yml) which is to run daily (schedule currently disabled) and invokes [a shell script](https://github.com/sqids/sqids-elixir/blob/f0b7a73/.github/workflows/default-blocklist-updater.sh) which runs [the Elixir updater script itself](https://github.com/sqids/sqids-elixir/blob/main/scripts/update_blocklist.exs), which automatically updates the dependency locks and the changelog upon there being any changes.

Upon that happening, a branch is pushed and a PR is opened.

All that's _likely_ missing is setting up additional permissions in the repo settings.

**Comment by 4kimov** [comment]
I'm not sure there's a need for automatic sync, since this will probably require some major code changes (in addition to blocklist changes). Blocklist updates will cause ID changes, so we'll have to carefully introduce this. As of now, no blocklist changes are scheduled.

**Comment by g-andrade** [comment]
That makes sense, I got ahead of myself. But no problem, the automation bits were for the most part copied from another lib I maintain.
