### ISSUE TITLE
Should the Hex package be owned by the Sqids org?

### ISSUE THREAD

**Issue by g-andrade** [sqids/sqids-elixir#5]
At the moment, I'm the sole owner: https://hex.pm/packages/sqids

Not ideal as far as the bus factor goes.

**Comment by 4kimov** [comment]
Thanks for pinging about this. I try to add other owners/maintainers when I can. If you'd like, you can add me: https://hex.pm/users/4kimov

**Comment by g-andrade** [comment]
> If you'd like, you can add me

Done :heavy_check_mark:
