### ISSUE TITLE
Update Sqids Elixir webpage

### ISSUE THREAD

**Issue by g-andrade** [sqids/sqids-elixir#6]
https://sqids.org/elixir

**Comment by 4kimov** [comment]
Thanks for finishing the lib. Website updated. Do [the examples](https://sqids.org/elixir) look correct?

**Comment by g-andrade** [comment]
> Do [the examples](https://sqids.org/elixir) look correct?

I tried all three and they are correct :+1: the reason why the equivalent examples in README have a bit more fluff (`iex> ` prefix and extra matches) is for them to be [detected as unit tests and run as such](https://github.com/sqids/sqids-elixir/blob/94164c04ff80a6ac112e0f033b25d8a1dc880f15/test/sqids_test.exs#L699-L704), which gives assurance that they're correct (or if they become outdated over time). 

Not ideal when copying them from GitHub, but at least in [the Hex docs](https://hexdocs.pm/sqids/readme.html) the copying action strips that stuff away and the copied code is runnable in an interactive Elixir shell.

In any case, it's 100% sensible for the examples in the website to be simpler.
